### PR TITLE
add faces

### PR DESCRIPTION
**Pull request by omar-polo**
Hello,

I thought that a bigger font for the title wouldn't look bad :)

The idea is to provide custom faces so users (and theme makers) can style the versuri buffer.  I've added two faces: one for the title and one for the text.

The default `:height 1.6` in the `versuri-lyrics-title-face` could be probably dropped if you don't like it.

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
Looks good!
Screenshot from 2021-11-04 12-57-13


Don't forget about the README, though.

**Comment by omar-polo** [comment]
I always forget the readme ^^"

would something like this be ok-ish?

**Comment by mihaiolteanu** [comment]
Perfect!

**Comment by omar-polo** [comment]
thanks :)

**Pull request merged**
